services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules

  api: 
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      - ./API:/app
      - /app/node_modules
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MAILER_DSN: ${MAILER_DSN}

  nginx: 
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./API:/var/www
      - ./API/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: